services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bektas
      POSTGRES_PASSWORD: bektas
      POSTGRES_DB: bektas_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
